name: CI
on: [push, pull_request]
jobs:
  cs-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: cache-composer
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/
          key: composer-8.1-${{ github.sha }}
      - name: setup
        uses: shivammathur/setup-php@2.24.0
        with:
          php-version: 8.0
          extensions: mbstring, fileinfo, json, intl, dom
      - name: composer install
        run: composer update --prefer-stable
      - name: 'php-cs-fixer check'
        run: composer cs-check
  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 15
      matrix:
        php-versions:  ['8.0', '8.1', '8.2']
    name: tests-${{ matrix.php-versions }}
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: cache-composer
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/
          key: composer-${{ matrix.php-versions }}-${{ github.sha }}
      - name: setup
        uses: shivammathur/setup-php@2.24.0
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, fileinfo, json, intl, dom
      - name: composer install
        run: composer update --prefer-stable
      - name: tests
        run: composer tests
  tests-lowest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: cache-composer-lowest
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/
          key: composer-lowest-${{ github.sha }}
      - name: setup
        uses: shivammathur/setup-php@2.24.0
        with:
          php-version: 8.0
          extensions: mbstring, fileinfo, json, intl, dom
      - name: composer install
        run: composer update --prefer-lowest --prefer-stable
      - name: tests
        run: composer tests
